### PR TITLE
Fix python install

### PR DESCRIPTION
**Pull request by adrisys**

### CODE REVIEW

**Comment by adriannavarrobetrian** [comment]
Hi Graham. This is for ticket https://seqera.freshdesk.com/a/tickets/4995.
Let me know if you are happy with it.

**Comment by gwright99** [comment]
@adriannavarrobetrian -- it's been awhile since I did this so I no longer have perfect recall but, IIRC, I started from a `debian` base because the image ended up being smaller (_although I think this may have been in comparison to the AWS python3 lambda image_).

What's the final size of the image generated by your PR vs updating the original debian approach? 
- If they are comparable, I think it makes sense to merge your PR to make things cleaner.
- If the Python3 image is way bigger, we should consider updating the original logic.

**Comment by adriannavarrobetrian** [comment]
```
❯ docker images debian:stable-slim
REPOSITORY   TAG           IMAGE ID       CREATED       SIZE
debian       stable-slim   660d0e209c30   12 days ago   97.2MB

❯ docker images python:3.9-slim-buster
REPOSITORY   TAG               IMAGE ID       CREATED         SIZE
python       3.9-slim-buster   bb1bad240fdf   11 months ago   110MB
```

They are similar.

**Comment by gwright99** [comment]
Alright, I'm not going to qibble about about ~10MiB.

@adriannavarrobetrian  - can you please add a screenshot of the new image working and I'll approve the PR?

**Comment by adriannavarrobetrian** [comment]
Screenshot 2024-05-06 at 15 36 46

**Review by gwright99 — APPROVED** [review]
LGTM

**Pull request merged**
